# Generated by Django 5.2 on 2025-04-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autho',
            new_name='author',
        ),
    ]
